version: '3'
services:

  fst-mongo:
    image: mongo
    volumes:
      - /private/var/lib/mongodb:/data/db
      - /private/var/log/feinstaub:/var/log
    ports:
      - '27017:27017'
    container_name: fst-mongo
#    command: '--auth'
    restart: always

  fst-data:
    image: fst-data
    volumes:
      - /private/var/log/feinstaub:/var/log
    environment:
      - TTS_KEY=YU4D8C6L39L53B8Q        
      - MONGOHOST=fst-mongo
#      - MONGOAUTH=true  
#      - "MONGOUSRP=rxf:5C5dB|m"  
    container_name: fst-data
    restart: always

#  fst-web:
#    image: fst-web
#    volumes:
#      - /private/var/log/feinstaub:/var/log
##      - "/etc/timezone:/etc/timezone:ro"
##      - "/etc/localtime:/etc/localtime:ro"
#    environment:
##      - VIRTUAL_HOST=feinstaub.rexfue.de
#      - MONGOHOST=fst-mongo
##      - MONGOAUTH=true  
##      - "MONGOUSRP=rxf:5C5dB|m"
#      - TZ=Europe/Berlin  
#    ports:
#      - '3005:3005'
#    container_name: fst-web
#    restart: always

